apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
- kube/nginx-resource.yaml  
- kube/node-app-namespace.yaml
- kube/workshop-deploy.yaml
- kube/workshop-service.yaml
- kube/tenant-identity.yaml