apiVersion: v1
kind: Service
metadata:
  labels:
    tier: web
  name: tenant-details-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tenant-details
  sessionAffinity: None
  type: ClusterIP
