apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../kube
namespace: k-tenant
commonLabels:
  tenant: k-tenant
configMapGenerator:
  - name: default-identity
    literals:
      - id="10"
      - name="k-tenant" 
